CREATE TABLE emp_detail
(
   tel varchar2(20),
   child number(2),
   age number(3),
   empno number(4)
      -- 제약조건
      CONSTRAINT emp_detail_EMP_EMPNO_fk -- 제약조건명(아무거나)
         REFERENCES EMP -- 참조테이블과 참조할 컬럼(컬럼을 명시하지않으면 자동으로 pk를 참조)
            ON DELETE cascade
)

INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01012345678', 0, 20, 7369);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01011122354', 1, 50, 7499);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01055566969', 0, 20, 7521);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01088965456', 1, 50, 7566);
INSERT INTO EMP_DETAIL(TEL, CHILD, AGE, EMPNO) VALUES('01077860023', 0, 20, 7654);
SELECT * FROM EMP_DETAIL;
SELECT * FROM EMP;
--1
SELECT E.EMPNO,E.ENAME,E.JOB,D.TEL,D.CHILD,D.AGE,DT.DNAME
FROM EMP E
INNER JOIN EMP_DETAIL D ON D.EMPNO = E.EMPNO
INNER JOIN DEPT DT ON E.DEPTNO = DT.DEPTNO 
--2
SELECT E.EMPNO,E.ENAME,E.JOB,D.TEL,D.CHILD,D.AGE,DT.DNAME
FROM EMP E 
LEFT JOIN EMP_DETAIL D ON E.EMPNO = D.EMPNO
INNER JOIN DEPT DT ON E.DEPTNO = DT.DEPTNO
--3
SELECT * FROM EMP E 
INNER JOIN EMP_DETAIL D ON E.EMPNO = D.EMPNO 
INNER JOIN DEPT DT ON E.DEPTNO = DT.DEPTNO  WHERE CHILD = 0;
--4 상세 정보 없는 사원 몇명인지 출력
SELECT COUNT(*) FROM EMP E LEFT JOIN EMP_DETAIL D ON E.EMPNO = D.EMPNO WHERE D.EMPNO IS NULL;
--5 사원의 평균 급여 출력
SELECT AVG(NVL(SAL,0)) FROM EMP E INNER JOIN EMP_DETAIL D ON E.EMPNO = D.EMPNO;
--6 DALLAS 군무 사원의 총 자녀 수 NVL(A,B) -> NULL인 VALUE A를 B로 바꾸기
SELECT SUM(NVL(CHILD, 0)) FROM EMP_DETAIL D INNER JOIN EMP E ON E.EMPNO = D.EMPNO INNER JOIN DEPT DT ON E.DEPTNO = DT.DEPTNO WHERE LOC='DALLAS';


SELECT EMPNO,ENAME,SAL,(SELECT AVG(SAL) FROM EMP) AS AVG FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP);



UPDATE EMP_DETAIL SET TEL = '1' WHERE EMPNO = 7369;
SELECT * FROM EMP_DETAIL;


